export const jsonData = [
  {
    "Name": "Sanket sett",
    "Year": "Fourth",
    "Department": "ECE",
    "Position": "All Rounder (Includes all position even GK)",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Veg",
    "Photo": "https://i.postimg.cc/TPzdSP0B/Screenshot-20240627-143928-Chrome-Sanket-Sett.jpg",
    "WhatsApp number": 7605816618
  },
  {
    "Name": "Rishav Kundu",
    "Year": "Second",
    "Department": "CSE",
    "Position": "All Rounder (Includes all position even GK)",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/C5jsDdr0/IMG-20240824-WA0021-1-Rishav-Kundu.jpg",
    "WhatsApp number": 9007096059
  },
  {
    "Name": "Rajdeep Pal",
    "Year": "Third",
    "Department": "AIML",
    "Position": "All Rounder (Includes all position even GK)",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/ZnHtHYCk/IMG-20240615-WA0037-Rajdeep-Pal.jpg",
    "WhatsApp number": 8240805226
  },
  {
    "Name": "Pratham Bhattacharjee",
    "Year": "Fourth",
    "Department": "ECE",
    "Position": "All Rounder (Includes all position even GK)",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/XqVbSBC1/IMG-0041-Pratham.jpg",
    "WhatsApp number": 123456789
  },
  {
    "Name": "Mahan Brata Raha",
    "Year": "Pass out (Batch 2024)",
    "Department": "IT",
    "Position": "All Rounder (Includes all position even GK)",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/2jPtZZ6s/IMG-20240416-WA0047-48-MAHAN-BRATA-RAHA.jpg",
    "WhatsApp number": 9903602580
  },
  {
    "Name": "Ayan Koley",
    "Year": "Third",
    "Department": "AIML",
    "Position": "All Rounder (Includes all position even GK)",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/pXLgxHmT/IMG-20240504-WA0008-Ayan-Koley.jpg",
    "WhatsApp number": 9088286433
  },
  {
    "Name": "Prakash pandey",
    "Year": "Third",
    "Department": "AIML",
    "Position": "All Rounder (Includes all position even GK)",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Veg",
    "Photo": "https://i.postimg.cc/qqbDgNN7/17247832908462512905038449785403-Prakash.jpg",
    "WhatsApp number": 9330173993
  },
  {
    "Name": "Himanshu Kumar",
    "Year": "Second",
    "Department": "AIML",
    "Position": "All Rounder (Includes all position even GK)",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/MT1Q3N7b/inbound634042185442174747-Himanshu-Kumar.jpg",
    "WhatsApp number": 7033583581
  },
  {
    "Name": "Sohom Bhuieya",
    "Year": "Fourth",
    "Department": "EE",
    "Position": "Goalkeeper",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/tTGbkMCj/IMG-0204-EE-09-Sohom-Bhuieya.jpg",
    "WhatsApp number": "9007398495="
  },
  {
    "Name": "Ayushman",
    "Year": "Fourth",
    "Department": "IT",
    "Position": "Goalkeeper",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/m2gsmMRt/IMG-20240826-191210-IT-48-Ayushman-Podder.jpg",
    "WhatsApp number": 7439489320
  },
  {
    "Name": "Apurv Krishn Jha",
    "Year": "Fourth",
    "Department": "AIML",
    "Position": "Goalkeeper",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/KYBS1D7s/100297235-Apurv-Krishn-Jha.jpg",
    "WhatsApp number": 9199707044
  },
  {
    "Name": "Md Adil Sehab",
    "Year": "Fourth",
    "Department": "IT",
    "Position": "Goalkeeper",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/Xvwmj73R/Adil-1-ADIL.jpg",
    "WhatsApp number": 6291227656
  },
  {
    "Name": "Chetan Singh",
    "Year": "Pass out (Batch 2024)",
    "Department": "EE",
    "Position": "Goalkeeper",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/QMXk7XcG/IMG-7802-Chetan-Singh.jpg",
    "WhatsApp number": 9051581112
  },
  {
    "Name": "Romit Bodhak",
    "Year": "Pass out (Batch 2024)",
    "Department": "IT",
    "Position": "Goalkeeper",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/mZ8x1DMR/IMG-20240826-WA0017-Azhan-Shadique.jpg",
    "WhatsApp number": 8337061338
  },
  {
    "Name": "Arghadip Chakraborty",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Goalkeeper",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/L8VQwQTS/IMG-6523-Arghadip-Chakraborty.jpg",
    "WhatsApp number": 7908119341
  },
  {
    "Name": "Nilangshu Ganguly",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Goalkeeper",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/9F5xMHgV/Retouch-Me-20240131085003880-Nilangshu.jpg",
    "WhatsApp number": 9330523053
  },
  {
    "Name": "Surajit Singh",
    "Year": "Second",
    "Department": "ECE",
    "Position": "Goalkeeper",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/prNBpKZk/IMG-20240725-WA0012-Surajit-Singh.jpg",
    "WhatsApp number": 7407194243
  },
  {
    "Name": "Zubair Ahmed Mullick",
    "Year": "Third",
    "Department": "AIML",
    "Position": "Goalkeeper",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/kgB3NmCZ/20240411-142012-Zubair-Ahmed-Mullick.jpg",
    "WhatsApp number": 9831315001
  },
  {
    "Name": "Arafat Khan",
    "Year": "Third",
    "Department": "EE",
    "Position": "Goalkeeper",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/Hx3BPr4t/Screenshot-2024-0830-143302-Arafat-Khan.jpg",
    "WhatsApp number": 6291039658
  },
  {
    "Name": "Debjit Goswami",
    "Year": "Fourth",
    "Department": "EE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/KjNmRDby/IMG-20210408-WA0136-EE-29-Debjit-Goswami.jpg",
    "WhatsApp number": 8918655966
  },
  {
    "Name": "Deepan Choudhury",
    "Year": "Fourth",
    "Department": "EE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/zXxJN7pC/IMG-20240203-WA0434-Deepan-Choudhury.jpg",
    "WhatsApp number": 9836579142
  },
  {
    "Name": "Tamal",
    "Year": "Fourth",
    "Department": "EE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/sg13gW0t/IMG20230613151800-TAMAL-GHOSH.jpg",
    "WhatsApp number": 9163661154
  },
  {
    "Name": "Indrabha Ghosh",
    "Year": "Fourth",
    "Department": "ECE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/13FYB5g8/IMG-20231118-121820-Indrabha-Ghosh.jpg",
    "WhatsApp number": 8981103931
  },
  {
    "Name": "Rajdeep Barik",
    "Year": "Fourth",
    "Department": "ECE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/gjrgZYFk/inbound623910524811417483-Rajdeep-Barik-06-ECE.webp",
    "WhatsApp number": 9732122004
  },
  {
    "Name": "Jishan",
    "Year": "Pass out (Batch 2023)",
    "Department": "EE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Veg",
    "Photo": "https://i.postimg.cc/zfj72LqG/IMG-20240825-074819-532-21-Jishan-Dhabak.webp",
    "WhatsApp number": 6289718898
  },
  {
    "Name": "Sayak Karui",
    "Year": "Pass out (Batch 2024)",
    "Department": "CSE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/Bb8CvMHj/IMG-20240825-154040-CSE-31-SAYAK-KARUI.jpg",
    "WhatsApp number": 6289590339
  },
  {
    "Name": "Afnan Hassan",
    "Year": "Pass out (Batch 2024)",
    "Department": "CSE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/VsTRhPPn/FECDA059-9703-4-D3-E-94-C0-1066-E5-FB70-A7-Afnan-Hassan.jpg",
    "WhatsApp number": 8335979945
  },
  {
    "Name": "Suvankar Dey",
    "Year": "Pass out (Batch 2024)",
    "Department": "CSE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/fT9KnqMF/Pics-Art-11-20-09-41-00-CSE-16-Suvankar-Dey.jpg",
    "WhatsApp number": 9007612944
  },
  {
    "Name": "Anuj Kumar Jha",
    "Year": "Pass out (Batch 2024)",
    "Department": "CSE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/vZwvQ7Bm/20240510-DSC04310-Anuj-Jha.jpg",
    "WhatsApp number": 9163090985
  },
  {
    "Name": "Md Misbahul Hoda",
    "Year": "Second",
    "Department": "AIML",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/J4Z2czHG/inbound4601614226850780259-MD-MISBAHUL-HODA.png",
    "WhatsApp number": 8002439311
  },
  {
    "Name": "Suryashekhar Das ( Joy )",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/yYjFzMwL/IMG-20240514-191104-JOY-OP.jpg",
    "WhatsApp number": 9609298284
  },
  {
    "Name": "Mohammad Mubashir",
    "Year": "Second",
    "Department": "IT",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/fTc8Sq1d/IMG-20240816-144451-409-Mohammad-Mubashir.webp",
    "WhatsApp number": 6289762052
  },
  {
    "Name": "Saiful islam",
    "Year": "Second",
    "Department": "IT",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/zfB7Mzvw/IMG-20240825-233148-Saiful-Islam.jpg",
    "WhatsApp number": 7603030287
  },
  {
    "Name": "Pratik Mazumder",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/KvD58kgr/Picsart-24-08-15-18-03-56-520-Pratik-Mazumder.jpg",
    "WhatsApp number": 9433899647
  },
  {
    "Name": "Suryakant Behera",
    "Year": "Second",
    "Department": "IT",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/76TZKzyF/Photo-SURYAKANT-BEHERA.jpg",
    "WhatsApp number": 7003266878
  },
  {
    "Name": "Shiv Narayan Roy",
    "Year": "Second",
    "Department": "ECE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/WbV17tYy/20240826-112515-Shiv-Narayan-Roy.jpg",
    "WhatsApp number": 9831979979
  },
  {
    "Name": "Aritra Ghosh",
    "Year": "Second",
    "Department": "ECE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/t4SRykR0/Whats-App-Image-2024-08-26-at-12-40-59-30959665-Aritra-Ghosh.jpg",
    "WhatsApp number": 9903998450
  },
  {
    "Name": "Rudrapriyo Chakraborty",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/fbVzbdkV/1693316450143-RUDRAPRIYO-CHAKRABORTY.jpg",
    "WhatsApp number": 9123091403
  },
  {
    "Name": "Bratin Roy",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/xdB0Ndbt/1724747816868569040898551963188-Bratin-Roy.jpg",
    "WhatsApp number": 9007076868
  },
  {
    "Name": "Aheen Goswami",
    "Year": "Second",
    "Department": "ECE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/VsqY5msW/inbound56387328289023836-Aheen-GOswami.jpg",
    "WhatsApp number": 7439554403
  },
  {
    "Name": "Debmalya Banerjee",
    "Year": "Third",
    "Department": "AIML",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/jdRR7mL0/IMG-20240825-123138-065-DEBMALYA-BANERJEE.jpg",
    "WhatsApp number": 7595971826
  },
  {
    "Name": "Soham Roy",
    "Year": "Third",
    "Department": "ECE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/Bn8kLBcf/IMG-20190316-055521-Soham-Roy.jpg",
    "WhatsApp number": 9123920402
  },
  {
    "Name": "Faizan Ahmed Khan",
    "Year": "Second",
    "Department": "AIML",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/s2kWcshg/IMG-3447-28-FAIZAN-HMED-KHAN.jpg",
    "WhatsApp number": 7980043806
  },
  {
    "Name": "Sagnik",
    "Year": "Third",
    "Department": "CSE",
    "Position": "Defender",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/3J73GRtx/IMG-20240903-WA0006.jpg",
    "WhatsApp number": 8981529015
  },
  {
    "Name": "Bishal Saha",
    "Year": "Fourth",
    "Department": "ECE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/xCLfSSF8/Screenshot-2024-08-25-23-56-17-06-a23b203fd3aafc6dcb84e438dda678b6-Bishal-Saha.jpg",
    "WhatsApp number": 9123038024
  },
  {
    "Name": "Shakcham Raj Gupta",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/j2TYygQF/IMG-20240829-WA0007.jpg",
    "WhatsApp number": 9433528336
  },
  {
    "Name": "Shaurya Chakraborty",
    "Year": "Fourth",
    "Department": "EE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/HkKdcLqj/IMG-4955-EE-Shaurya-Chakraborty.jpg",
    "WhatsApp number": 9830389581
  },
  {
    "Name": "Souvick Pradhan",
    "Year": "Fourth",
    "Department": "ECE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/h4rn8skk/IMG-7677-Souvick-Pradhan.jpg",
    "WhatsApp number": 8670022447
  },
  {
    "Name": "Tathagata Das",
    "Year": "Fourth",
    "Department": "CSE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/NjRpTJVT/DSC-0417-CSE-16-Tathagata-Das.jpg",
    "WhatsApp number": 8972424871
  },
  {
    "Name": "Srijit Sarkhel",
    "Year": "Pass out (Batch 2024)",
    "Department": "IT",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/vBZzJQmL/IMG-20240825-WA0044-60-Srijit-Sarkhel.jpg",
    "WhatsApp number": 9073512366
  },
  {
    "Name": "Rahul Konar",
    "Year": "Pass out (Batch 2024)",
    "Department": "CSE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/gJ7v18Qm/20221112-145450-Rahul.jpg",
    "WhatsApp number": 9330941799
  },
  {
    "Name": "Farzan Reza",
    "Year": "Pass out (Batch 2024)",
    "Department": "EE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/44KMy5Jv/E53-E061-E-1452-46-C4-8878-11-E58-E6313-CA-EE-32-FARZAN-REZA.jpg",
    "WhatsApp number": 8617751021
  },
  {
    "Name": "Aryan Agarwal",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/MGK3S0PQ/Photograph-Aryan-Agarwal.jpg",
    "WhatsApp number": 9830670760
  },
  {
    "Name": "Shahil Paul",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/MGPPKcNr/IMG20240510205234-50-Shahil-Paul-XIA.jpg",
    "WhatsApp number": 9836483805
  },
  {
    "Name": "Sayan Maity",
    "Year": "Second",
    "Department": "AIML",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Veg",
    "Photo": "https://i.postimg.cc/Mpzd7b8F/IMG-20240309-WA0004-Sayan-Maity.jpg",
    "WhatsApp number": 8328749251
  },
  {
    "Name": "Adil Nawaz Alam",
    "Year": "Second",
    "Department": "AIML",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/0NbGnVXc/IMG-20220825-WA0007-ADIL-NAWAZ-ALAM.jpg",
    "WhatsApp number": 9830578704
  },
  {
    "Name": "Moyukh Das",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/xdhv4LWY/IMG-20240503-152902-228-Moyukh-Das.jpg",
    "WhatsApp number": 9874800695
  },
  {
    "Name": "Gauhar Akram",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/W3ZGLhvZ/Photo-Gauhar-Akram.jpg",
    "WhatsApp number": 9038143108
  },
  {
    "Name": "Milind Lodh",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/90jGWCmn/IMG-20240826-000316-Milind-Lodh.jpg",
    "WhatsApp number": 9831312285
  },
  {
    "Name": "Ritam Chakraborty",
    "Year": "Second",
    "Department": "IT",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/TYjp8nWG/Screenshot-2024-0826-003733-Ritam-Chakraborty.jpg",
    "WhatsApp number": 6291715353
  },
  {
    "Name": "Md Imroz Akram",
    "Year": "Second",
    "Department": "AIML",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/nr4cJtrT/Snapchat-2040774400-Imroz-Akram.jpg",
    "WhatsApp number": 9534579798
  },
  {
    "Name": "Bikash Manna",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/nc1cSZ6h/IMG-20240510-WA0030-Bikash-Manna.jpg",
    "WhatsApp number": 8016165938
  },
  {
    "Name": "Aranyak Ghosh",
    "Year": "Second",
    "Department": "ECE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/ZR3J8h8Z/20240822-161756-Aranyak-Ghosh.jpg",
    "WhatsApp number": 8420956870
  },
  {
    "Name": "Ahbab Khan",
    "Year": "Second",
    "Department": "IT",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/nrJpTw2m/PHOTO-2023-04-12-19-57-00-2-Ahbab-Ahmed-Khan.jpg",
    "WhatsApp number": 9330848344
  },
  {
    "Name": "Suvodip Mahata",
    "Year": "Second",
    "Department": "EE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Veg",
    "Photo": "https://i.postimg.cc/x83YZyp4/IMG-20230831-104254-Suvo-Mahata.jpg",
    "WhatsApp number": 8617502528
  },
  {
    "Name": "Agniva",
    "Year": "Third",
    "Department": "IT",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/bNLpHgtG/IMG-20231022-WA0237-01-Agniva-Acherjee.jpg",
    "WhatsApp number": 6289634778
  },
  {
    "Name": "Md Daris Iqbal",
    "Year": "Third",
    "Department": "AIML",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Veg",
    "Photo": "https://i.postimg.cc/rpRTTLYW/Screenshot-20221110-131420-Gallery-MOHAMMED-DARIS-IQBAL.jpg",
    "WhatsApp number": 8697470722
  },
  {
    "Name": "Sayanavo bhattacherjee",
    "Year": "Third",
    "Department": "EE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/hPCR7GkT/IMG-20240816-143130-268-Sayanavo-Bhattacherjee.webp",
    "WhatsApp number": 7439432594
  },
  {
    "Name": "Rezaul Haque",
    "Year": "Third",
    "Department": "AIML",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/7L0RXPWB/3399285-A-849-B-422-B-BD48-019-CA7-F285-F2-21-REZAUL-HAQUE.jpg",
    "WhatsApp number": 7439315210
  },
  {
    "Name": "Sarthak",
    "Year": "Third",
    "Department": "CSE",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/j2dksHd9/IMG-20200924-WA0022-Sarthak-Pal.jpg",
    "WhatsApp number": 8910393092
  },
  {
    "Name": "Akash Debnath",
    "Year": "Third",
    "Department": "IT",
    "Position": "Midfielder",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/sDL0rZF6/inbound8556155266149814396-Akash-Debnath-IT-16.jpg",
    "WhatsApp number": 9051755350
  },
  {
    "Name": "Sayak Hajra",
    "Year": "Fourth",
    "Department": "CSE",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/jdxsBm6q/Screenshot-2024-08-25-01-57-36-54-965bbf4d18d205f782c6b8409c5773a4-Sayak-Hajra.jpg",
    "WhatsApp number": 9231579076
  },
  {
    "Name": "Ritam Datta",
    "Year": "Fourth",
    "Department": "EE",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/R0QprsL9/IMG-20240722-WA0029-Ritam-Datta.jpg",
    "WhatsApp number": 6289801124
  },
  {
    "Name": "Arka Dastidar",
    "Year": "Pass out (Batch 2024)",
    "Department": "CSE",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/50K31ZYc/15-Arka-CSE-Arka-Dastidar.jpg",
    "WhatsApp number": 8335017702
  },
  {
    "Name": "Soumarya Ghosh",
    "Year": "Second",
    "Department": "ECE",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/NFTp4dMW/IMG-20240822-WA0115-Soumarya-Ghosh.jpg",
    "WhatsApp number": 6290292845
  },
  {
    "Name": "Rajdeep Jana",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/KcLNCsGW/Screenshot-2023-04-29-19-00-05-127-com-adobe-reader-Rajdeep-Jana.png",
    "WhatsApp number": 9330977202
  },
  {
    "Name": "Md Junaid Mullick",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/yxX0xtWY/cdce7eb3-3d27-4730-a273-ef6f15ea6194-Junaid-Mullick.jpg",
    "WhatsApp number": 6289337090
  },
  {
    "Name": "Souranshu",
    "Year": "Second",
    "Department": "IT",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/0QmcPtsc/0-B5-C4165-F082-4-B65-8-FED-6-EBF283648-A2-Souranshu-Panda.jpg",
    "WhatsApp number": 8700204134
  },
  {
    "Name": "Asif Reja",
    "Year": "Second",
    "Department": "CSE",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/MpKZhNSb/IMG-4005-Asif-Reja.jpg",
    "WhatsApp number": 9832283580
  },
  {
    "Name": "Akash Hajra",
    "Year": "Third",
    "Department": "IT",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "No",
    "Have you played Inter-departmental football tournament?": "No",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/NMv3w2Xq/Picsart-24-07-27-00-12-31-115-Akash-Hajra.jpg",
    "WhatsApp number": 8100680500
  },
  {
    "Name": "Sristinil Biswas",
    "Year": "Third",
    "Department": "IT",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/pTQgVVQ9/1000470147-SRISTINIL-BISWAS.jpg",
    "WhatsApp number": 7044709994
  },
  {
    "Name": "Srinjoy Chowdhury",
    "Year": "Third",
    "Department": "ECE",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/VvDpM7Vm/meself-Srinjoy-Chowdhury.jpg",
    "WhatsApp number": 9836512835
  },
  {
    "Name": "Saran",
    "Year": "Fourth",
    "Department": "ECE",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/6qhJcrM5/IMG-20240903-WA0014.jpg",
    "WhatsApp number": 7980770458
  },
  {
    "Name": "Jishnu Nath",
    "Year": "Third",
    "Department": "AIML",
    "Position": "Striker",
    "Have you played RSTC 2.0?": "Yes",
    "Have you played Inter-departmental football tournament?": "Yes",
    "Food preference?": "Non veg",
    "Photo": "https://i.postimg.cc/qRr5FVfp/Pics-Art-09-25-08-58-47-Jishnu-Nath.jpg",
    "WhatsApp number": "75968 99985"
  },
]